services:
  surstromming:
    image: surstromming
    container_name: surstromming
    stdin_open: true
    tty: true
    volumes:
      - ../sardine-config/:/root/.local/share/Sardine
      - ../projects/:/app/projects/
